import socket, time
s = socket.socket()
s.connect(('127.0.0.1', 4444))
time.sleep(1)
s.send(b'\n')
time.sleep(1)
s.recv(1024)
s.send(b'ls -l /usr/bin/nira-greeter > /tmp/check.txt\n')
time.sleep(1)
s.recv(1024)
s.send(b'ldd /usr/bin/nira-greeter >> /tmp/check.txt\n')
time.sleep(1)
s.recv(1024)
s.send(b'cat /tmp/check.txt\n')
time.sleep(1)
print(s.recv(65536).decode(), end='')
