[Distribution]
Distribution=arch
Mirror=http://mirrors.edge.kernel.org/archlinux/

[Output]
Format=disk
Output=NiraOS

[Content]
Bootable=yes
Bootloader=systemd-boot
ExtraTrees=mkosi/mkosi.extra
KernelCommandLine=console=ttyS0 loglevel=6 systemd.firstboot=0 systemd.unit=graphical.target
Timezone=UTC
Locale=C.UTF-8
Hostname=NiraOS
Packages=
    base
    linux
    systemd
    systemd-sysvcompat
    dbus
    mesa
    vulkan-radeon
    vulkan-intel
    pipewire
    pipewire-pulse
    networkmanager
    greetd
    sudo
    polkit
    qt6-wayland
    qt6-base
    qt6-declarative
    grpc
    protobuf
    wayland
    libinput
    xkeyboard-config
    ttf-dejavu
    breeze-icons
    breeze-cursors
    dbus-broker
    desktop-file-utils
    xdg-utils
    falkon
    pyside6
    qterminal
    htop
BuildPackages=
    rust
    protobuf
    cmake
    ninja
    gcc
    clang
    make
    pkgconf
    qt6-base
    qt6-declarative
    qt6-wayland
    vulkan-headers
    grpc

[Build]
WorkspaceDirectory=/root/mkosi-workspace
CacheDirectory=/root/mkosi-cache
BuildDirectory=/root/mkosi-build
WithNetwork=yes
Environment=
    LANG=C.UTF-8
